#----------------------------------
#       EntityTrackerFixer
#
#         By: Esmorall
#
#----------------------------------

#Log when the plugin untrack entities
log-to-console: true

#disable tick for untracked entities (experimental, use at your own risk)
disable-tick-for-untracked-entities: false

#How many ticks between untrack process
#The untrack process will check for untracked entities by players but still by the server, and untrack them.
untrack-ticks: 400

#if tps are not below this value, the task will not perform the untrack and it will wait for the next run
tps-limit: 19.5

#frecuency in ticks to check untracked entities
#It will check for players traking entities and will track it again (this is to prevent invisible entities)
check-untracked-entities-frequency: 40

#Distance in blocks to check for players near untracked entities
tracking-range: 30

#which worlds do you want the plugin to take effect?
worlds:
  - world
  - world_nether
  - world_the_end

#blacklisted entities that should not be impacted by the plugin
#you can find the list of all entities here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
blacklist:
  - ITEM_FRAME
  - ENDER_DRAGON
  - WITHER