name: EntityTrackerFixer
main: net.minemora.entitytrackerfixer.EntityTrackerFixer
version: 1.3.4 (Unofficial)_Hotfix1
softdepend: [Vault]
api-version: 1.14
author: Esmorall
description: Untrack entities that are not used at all by the server.
commands:
  entitytrackerfixer:
    aliases: [etf]
    description: Main command of EntityTrackerFixer.
    usage: /etf
permissions:
  entitytrackerfixer.*:
    children:
      - entitytrackerfixer.reload
  entitytrackerfixer.reload:
    default: op